languageCode = "en-us"
title = "The Croft Cookbook"
baseurl = "https://cookbook.bedewell.com"
paginate = 12 # To specify a multiple of 3
copyright = "© 2019 <a class=\"sitename\" href=\"https://www.bedewell.com/\">bedewell.com</a>"


theme = "cookbook-theme"

[params]
  description = "A Cookbook for the masses" # optional
  twitter = "josmartin1" # optional
  github = "josmartin" # optional
  headerCover = "images/headerCover.jpg" # optional
  footerCover = "images/footerCover.jpg"
  
[taxonomies]
  course = "courses"
  tag = "tags"
